site_name: ChemMatData
nav:
  - Introduction: index.md
  - Getting Started:
    - Installation: installation.md
    - First steps: first_steps.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.expand
